- [ ] CI/CD pipelines and DevOps methodologies (Jenkins).
- [ ] Cloud infrastructure platforms (AWS, GCP, Azure).
- [ ] Containerization and orchestration tools (Docker, Kubernetes)
- [ ] Problem solving skills (Leetcode?)
- [ ] Message queue (Apache Kafka)
- [ ] Unit, integration testing (Mockito, JUnit 5, Test Containers)
- [ ] RESTful api. GraphQL.
- [ ] Databases. PostgreSQL, MongoDB, Redis (SQL and NoSQL).